In [12]:
import pandas as pd
import os

In [13]:
amazon = pd.read_csv(
    "dataset/sentiment labelled sentences/amazon_cells_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/sentiment labelled sentences/amazon_cells_labelled.txt'

In [ ]:
imdb = pd.read_csv(
    "dataset/sentiment labelled sentences/imdb_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

NameError: name 'pd' is not defined

In [9]:
import sys
print(sys.executable)

c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

In [10]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.5 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/9.8 MB 1.8 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.8 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:06
   --------- ------------------------------ 2.4/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.5 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.8 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.7 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.8 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:06
Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 1.6 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.5 MB 1.9 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.5 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.5 MB 1.4 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.5 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.5 MB 1.4 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/12.5 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.5 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.5 MB 1.6 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.5 MB 1.6 MB/s eta 0:00:06
   ------------ --------------------------- 3.9/12.5 MB 1.5 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.5 MB 1.5 MB/s eta 0:00:06
   --------------- ------------------------ 4.7/12.5 MB 1.6 MB/s eta 0:00:05
   --------------- ------------------------ 5.0/12.5 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.5 MB 1.6 MB/s eta 0:00:05
   ------------------- -------------------- 6.0/12.5 MB 1.7 MB/s eta 0:00:04
   --------------------- ------------------ 6.6/12.5 MB 1.7 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.5 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.5 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.5 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.5 MB 1.7 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.5 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.5 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.5 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.5 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.5 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.5 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.5 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.5 MB 1.5 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.5 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.5 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.5 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.5 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.5 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.5 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.5 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.5 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.5 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 1.3 MB/s  0:00:09
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

In [11]:
import pandas as pd
print(pd.__version__)

3.0.5

In [14]:
import os

print(os.getcwd())

c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment

In [15]:
print(os.listdir())

['.venv', 'Dataset', 'model_building.ipynb']

In [16]:
amazon = pd.read_csv(
    "dataset/sentiment labelled sentences/sentiment labelled sentences/amazon_cells_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/sentiment labelled sentences/sentiment labelled sentences/amazon_cells_labelled.txt'

In [17]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFolders/files here:")
for item in os.listdir():
    print(item)

Current folder:
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment

Folders/files here:
.venv
Dataset
model_building.ipynb

In [18]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file == "amazon_cells_labelled.txt":
            print("FOUND:")
            print(os.path.join(root, file))

FOUND:
.\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt

In [21]:
import os

for root, dirs, files in os.walk(r"C:\Users\Dell\OneDrive\Desktop"):
    for file in files:
        if file.lower() == "amazon_cells_labelled.txt":
            print("FOUND:")
            print(os.path.join(root, file))

FOUND:
C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt

In [24]:
import os
import pandas as pd

# Find the file automatically
amazon_file = None

for root, dirs, files in os.walk(r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment"):
    for file in files:
        if file.lower() == "amazon_cells_labelled.txt":
            amazon_file = os.path.join(root, file)
            break
    if amazon_file:
        break

print("File found at:")
print(amazon_file)

File found at:
C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt

In [25]:
amazon = pd.read_csv(
    amazon_file,
    sep="\t",
    header=None,
    names=["text", "label"]
)

amazon.head()

                                                text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

In [26]:
print("Amazon shape:", amazon.shape)
print(amazon["label"].value_counts())

Amazon shape: (1000, 2)
label
0    500
1    500
Name: count, dtype: int64

In [27]:
imdb_file = None

for root, dirs, files in os.walk(r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment"):
    for file in files:
        if file.lower() == "imdb_labelled.txt":
            imdb_file = os.path.join(root, file)
            break
    if imdb_file:
        break

print("IMDB file found at:")
print(imdb_file)

IMDB file found at:
C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\imdb_labelled.txt

In [28]:
imdb = pd.read_csv(
    imdb_file,
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb.head()

                                                text  label
0  A very, very, very slow-moving, aimless movie ...      0
1  Not sure who was more lost - the flat characte...      0
2  Attempting artiness with black & white and cle...      0
3       Very little music or anything to speak of.        0
4  The best scene in the movie was when Gerardo i...      1

In [29]:
yelp_file = None

for root, dirs, files in os.walk(
    r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment"
):
    for file in files:
        if file.lower() == "yelp_labelled.txt":
            yelp_file = os.path.join(root, file)
            break
    if yelp_file:
        break

print("Yelp file found at:")
print(yelp_file)

Yelp file found at:
C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\yelp_labelled.txt

In [30]:
yelp = pd.read_csv(
    yelp_file,
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp.head()

                                                text  label
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [31]:
print("Amazon:", amazon.shape)
print("IMDB:", imdb.shape)
print("Yelp:", yelp.shape)

Amazon: (1000, 2)
IMDB: (748, 2)
Yelp: (1000, 2)

In [32]:
df = pd.concat(
    [amazon, imdb, yelp],
    ignore_index=True
)

df.head()

                                                text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

In [33]:
print("Final dataset shape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nMissing values:")
print(df.isnull().sum())

print("\nSentiment distribution:")
print(df["label"].value_counts())

Final dataset shape: (2748, 2)

Columns:
Index(['text', 'label'], dtype='str')

Missing values:
text     0
label    0
dtype: int64

Sentiment distribution:
label
1    1386
0    1362
Name: count, dtype: int64

In [34]:
print(df["label"].value_counts(normalize=True) * 100)

label
1    50.436681
0    49.563319
Name: proportion, dtype: float64

In [35]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
text     0
label    0
dtype: int64

In [36]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 17

In [37]:
display(df.sample(10, random_state=42))

                                                   text  label
2516  It's close to my house, it's low-key, non-fanc...      1
2642  If you stay in Vegas you must get breakfast he...      1
1359  Let's start with all the problemsthe acting, ...      0
1702  It's too bad that everyone else involved didn'...      0
2660  i felt insulted and disrespected, how could yo...      0
564   Yet Plantronincs continues to use the same fla...      0
1330  Whatever prompted such a documentary is beyond...      0
2375  Any grandmother can make a roasted chicken bet...      0
695          Do NOT buy if you want to use the holster.      0
321   I ordered this product first and was unhappy w...      0

In [38]:
df = df.drop_duplicates().reset_index(drop=True)

print("Dataset shape after removing duplicates:", df.shape)
print("Duplicate rows remaining:", df.duplicated().sum())

Dataset shape after removing duplicates: (2731, 2)
Duplicate rows remaining: 0

In [39]:
print(df.isnull().sum())

text     0
label    0
dtype: int64

In [41]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from scikit-learn) (2.5.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.25.0-py3-none-any.whl (467 kB)
Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   -- ------------------------------------- 2.6/36.6 MB 13.0 MB/s eta 0:00:03
   ------ --------------------------------- 5.5/36.6 MB 13.2 MB/s eta 0:00:03
   --------- ------------------------------ 8.4/36.6 MB 13.2 MB/s eta 0:00:03
   ------------- -------------------------- 12.3/36.6 MB 14.6 MB/s eta 0:00:02
   ------------------ --------------------- 16.8/36.6 MB 15.8 MB/s eta 0:00:02
   ---------------------- ----------------- 20.7/36.6 MB 16.5 MB/s eta 0:00:01
   --------------------------- ------------ 25.4/36.6 MB 17.2 MB/s eta 0:00:01
   ------------------------------- -------- 28.6/36.6 MB 17.5 MB/s eta 0:00:01
   ---------------------------------- ----- 32.0/36.6 MB 16.8 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 16.0 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 15.7 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 14.0 MB/s  0:00:02
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.25.0 scikit-learn-1.9.0 scipy-1.18.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [42]:
from sklearn.model_selection import train_test_split

print("Scikit-learn is working!")

Scikit-learn is working!

In [43]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print("Training data:", train_df.shape)
print("Testing data:", test_df.shape)

Training data: (2184, 2)
Testing data: (547, 2)

In [44]:
%pip install transformers datasets

Collecting transformers
  Downloading transformers-5.15.1-py3-none-any.whl.metadata (32 kB)
Collecting datasets
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.28.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers) (2.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers) (26.3)
Collecting pyyaml>=5.1 (from transformers)
  Downloading pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.7.19-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers)
  Downloading typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting tqdm>=4.60 (from transformers)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading filelock-3.32.4-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-25.0.1-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from datasets) (3.0.5)
Collecting requests>=2.32.2 (from datasets)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting xxhash (from datasets)
  Downloading xxhash-4.0.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.14.3-cp313-cp313-win_amd64.whl.metadata (8.5 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading propcache-0.5.2-cp313-cp313-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets)
  Downloading yarl-1.24.5-cp313-cp313-win_amd64.whl.metadata (107 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Downloading charset_normalizer-3.5.1-cp313-cp313-win_amd64.whl.metadata (46 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading transformers-5.15.1-py3-none-any.whl (11.7 MB)
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.7 MB 11.1 MB/s eta 0:00:01
   ------------------ --------------------- 5.5/11.7 MB 13.1 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.7 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------- 11.7/11.7 MB 14.5 MB/s  0:00:00
Downloading huggingface_hub-1.28.0-py3-none-any.whl (793 kB)
   ---------------------------------------- 0.0/793.2 kB ? eta -:--:--
   ---------------------------------------- 793.2/793.2 kB 15.5 MB/s  0:00:00
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 21.3 MB/s  0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 18.4 MB/s  0:00:00
Downloading datasets-5.0.1-py3-none-any.whl (559 kB)
   ---------------------------------------- 0.0/559.1 kB ? eta -:--:--
   ---------------------------------------- 559.1/559.1 kB 12.9 MB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.6.0-py3-none-any.whl (203 kB)
Downloading multiprocess-0.70.19-py313-none-any.whl (156 kB)
Downloading aiohttp-3.14.3-cp313-cp313-win_amd64.whl (476 kB)
Downloading multidict-6.7.1-cp313-cp313-win_amd64.whl (45 kB)
Downloading yarl-1.24.5-cp313-cp313-win_amd64.whl (97 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading filelock-3.32.4-py3-none-any.whl (99 kB)
Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl (43 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.19-py3-none-any.whl (68 kB)
Downloading propcache-0.5.2-cp313-cp313-win_amd64.whl (41 kB)
Downloading pyarrow-25.0.1-cp313-cp313-win_amd64.whl (27.9 MB)
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
   --- ------------------------------------ 2.6/27.9 MB 12.0 MB/s eta 0:00:03
   --------- ------------------------------ 6.8/27.9 MB 15.6 MB/s eta 0:00:02
   ---------------- ----------------------- 11.3/27.9 MB 17.7 MB/s eta 0:00:01
   -------------------- ------------------- 14.2/27.9 MB 16.4 MB/s eta 0:00:01
   ---------------------- ----------------- 15.5/27.9 MB 14.6 MB/s eta 0:00:01
   ------------------------ --------------- 17.3/27.9 MB 13.7 MB/s eta 0:00:01
   --------------------------- ------------ 18.9/27.9 MB 13.2 MB/s eta 0:00:01
   ------------------------------- -------- 22.3/27.9 MB 13.1 MB/s eta 0:00:01
   -------------------------------------- - 26.7/27.9 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 27.9/27.9 MB 13.2 MB/s  0:00:02
Downloading pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Downloading regex-2026.7.19-cp313-cp313-win_amd64.whl (277 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-win_amd64.whl (199 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Downloading typer-0.27.1-py3-none-any.whl (122 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading xxhash-4.0.1-cp313-cp313-win_amd64.whl (36 kB)
Installing collected packages: xxhash, urllib3, tqdm, shellingham, safetensors, regex, pyyaml, pyarrow, propcache, multidict, mdurl, idna, hf-xet, h11, fsspec, frozenlist, filelock, dill, click, charset_normalizer, certifi, attrs, annotated-doc, aiohappyeyeballs, yarl, requests, multiprocess, markdown-it-py, httpcore, anyio, aiosignal, rich, httpx, aiohttp, typer, huggingface-hub, tokenizers, datasets, transformers

   - --------------------------------------  1/39 [urllib3]
   - --------------------------------------  1/39 [urllib3]
   -- -------------------------------------  2/39 [tqdm]
   -- -------------------------------------  2/39 [tqdm]
   -- -------------------------------------  2/39 [tqdm]
   ---- -----------------------------------  4/39 [safetensors]
   ----- ----------------------------------  5/39 [regex]
   ----- ----------------------------------  5/39 [regex]
   ------ ---------------------------------  6/39 [pyyaml]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   ------- --------------------------------  7/39 [pyarrow]
   --------- ------------------------------  9/39 [multidict]
   ----------- ---------------------------- 11/39 [idna]
   ------------ --------------------------- 12/39 [hf-xet]
   ------------- -------------------------- 13/39 [h11]
   -------------- ------------------------- 14/39 [fsspec]
   -------------- ------------------------- 14/39 [fsspec]
   -------------- ------------------------- 14/39 [fsspec]
   -------------- ------------------------- 14/39 [fsspec]
   -------------- ------------------------- 14/39 [fsspec]
   ---------------- ----------------------- 16/39 [filelock]
   ---------------- ----------------------- 16/39 [filelock]
   ---------------- ----------------------- 16/39 [filelock]
   ----------------- ---------------------- 17/39 [dill]
   ----------------- ---------------------- 17/39 [dill]
   ----------------- ---------------------- 17/39 [dill]
   ------------------ --------------------- 18/39 [click]
   ------------------ --------------------- 18/39 [click]
   ------------------- -------------------- 19/39 [charset_normalizer]
   -------------------- ------------------- 20/39 [certifi]
   --------------------- ------------------ 21/39 [attrs]
   ----------------------- ---------------- 23/39 [aiohappyeyeballs]
   ------------------------ --------------- 24/39 [yarl]
   ------------------------- -------------- 25/39 [requests]
   ------------------------- -------------- 25/39 [requests]
   -------------------------- ------------- 26/39 [multiprocess]
   -------------------------- ------------- 26/39 [multiprocess]
   -------------------------- ------------- 26/39 [multiprocess]
   -------------------------- ------------- 26/39 [multiprocess]
   --------------------------- ------------ 27/39 [markdown-it-py]
   --------------------------- ------------ 27/39 [markdown-it-py]
   --------------------------- ------------ 27/39 [markdown-it-py]
   --------------------------- ------------ 27/39 [markdown-it-py]
   ---------------------------- ----------- 28/39 [httpcore]
   ---------------------------- ----------- 28/39 [httpcore]
   ---------------------------- ----------- 28/39 [httpcore]
   ---------------------------- ----------- 28/39 [httpcore]
   ----------------------------- ---------- 29/39 [anyio]
   ----------------------------- ---------- 29/39 [anyio]
   ----------------------------- ---------- 29/39 [anyio]
   ----------------------------- ---------- 29/39 [anyio]
   ----------------------------- ---------- 29/39 [anyio]
   ----------------------------- ---------- 29/39 [anyio]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   ------------------------------- -------- 31/39 [rich]
   -------------------------------- ------- 32/39 [httpx]
   -------------------------------- ------- 32/39 [httpx]
   -------------------------------- ------- 32/39 [httpx]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   --------------------------------- ------ 33/39 [aiohttp]
   ---------------------------------- ----- 34/39 [typer]
   ---------------------------------- ----- 34/39 [typer]
   ---------------------------------- ----- 34/39 [typer]
   ---------------------------------- ----- 34/39 [typer]
   ---------------------------------- ----- 34/39 [typer]
   ---------------------------------- ----- 34/39 [typer]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ----------------------------------- ---- 35/39 [huggingface-hub]
   ------------------------------------ --- 36/39 [tokenizers]
   ------------------------------------ --- 36/39 [tokenizers]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   ------------------------------------- -- 37/39 [datasets]
   -------------------------------------- - 38/39 [transformers]
   -------------------------------------- - 38/39 [transformers]

In [45]:
from transformers import AutoTokenizer

print("Transformers is working!")

c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

Transformers is working!

In [46]:
tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

print("Tokenizer loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dell\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Tokenizer loaded successfully!

In [47]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

print(train_dataset)
print(test_dataset)

Dataset({
    features: ['text', 'label', '__index_level_0__'],
    num_rows: 2184
})
Dataset({
    features: ['text', 'label', '__index_level_0__'],
    num_rows: 547
})

In [48]:
train_dataset = train_dataset.remove_columns(["__index_level_0__"])
test_dataset = test_dataset.remove_columns(["__index_level_0__"])

print(train_dataset)

Dataset({
    features: ['text', 'label'],
    num_rows: 2184
})

In [49]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

In [50]:
tokenized_train = train_dataset.map(
    tokenize_function,
    batched=True
)

tokenized_test = test_dataset.map(
    tokenize_function,
    batched=True
)

Map: 100%|██████████| 2184/2184 [00:01<00:00, 1320.45 examples/s]
Map: 100%|██████████| 547/547 [00:00<00:00, 2371.66 examples/s]

In [52]:
%pip install torch

Collecting torch
  Downloading torch-2.13.0-cp313-cp313-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: filelock in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (80.9.0)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (2026.6.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading torch-2.13.0-cp313-cp313-win_amd64.whl (122.1 MB)
   ---------------------------------------- 0.0/122.1 MB ? eta -:--:--
   - -------------------------------------- 3.1/122.1 MB 16.9 MB/s eta 0:00:08
   - -------------------------------------- 5.5/122.1 MB 13.6 MB/s eta 0:00:09
   -- ------------------------------------- 8.9/122.1 MB 13.8 MB/s eta 0:00:09
   ---- ----------------------------------- 12.3/122.1 MB 14.7 MB/s eta 0:00:08
   ----- ---------------------------------- 16.3/122.1 MB 15.2 MB/s eta 0:00:07
   ------ --------------------------------- 19.4/122.1 MB 15.1 MB/s eta 0:00:07
   ------- -------------------------------- 22.5/122.1 MB 15.1 MB/s eta 0:00:07
   -------- ------------------------------- 24.6/122.1 MB 14.3 MB/s eta 0:00:07
   -------- ------------------------------- 26.5/122.1 MB 13.6 MB/s eta 0:00:08
   --------- ------------------------------ 29.4/122.1 MB 13.6 MB/s eta 0:00:07
   ---------- ----------------------------- 32.5/122.1 MB 13.7 MB/s eta 0:00:07
   ----------- ---------------------------- 36.2/122.1 MB 13.9 MB/s eta 0:00:07
   ------------ --------------------------- 39.6/122.1 MB 14.1 MB/s eta 0:00:06
   -------------- ------------------------- 43.0/122.1 MB 14.3 MB/s eta 0:00:06
   --------------- ------------------------ 46.1/122.1 MB 14.2 MB/s eta 0:00:06
   ---------------- ----------------------- 49.3/122.1 MB 14.3 MB/s eta 0:00:06
   ----------------- ---------------------- 51.9/122.1 MB 14.2 MB/s eta 0:00:05
   ----------------- ---------------------- 54.8/122.1 MB 14.1 MB/s eta 0:00:05
   ------------------ --------------------- 57.4/122.1 MB 14.0 MB/s eta 0:00:05
   ------------------- -------------------- 60.6/122.1 MB 14.0 MB/s eta 0:00:05
   -------------------- ------------------- 63.7/122.1 MB 14.1 MB/s eta 0:00:05
   --------------------- ------------------ 65.3/122.1 MB 13.8 MB/s eta 0:00:05
   ---------------------- ----------------- 67.9/122.1 MB 13.7 MB/s eta 0:00:04
   ---------------------- ----------------- 69.5/122.1 MB 13.4 MB/s eta 0:00:04
   ---------------------- ----------------- 70.0/122.1 MB 13.1 MB/s eta 0:00:04
   ----------------------- ---------------- 71.3/122.1 MB 12.8 MB/s eta 0:00:04
   ------------------------ --------------- 73.4/122.1 MB 12.7 MB/s eta 0:00:04
   ------------------------ --------------- 75.5/122.1 MB 12.5 MB/s eta 0:00:04
   ------------------------- -------------- 78.1/122.1 MB 12.5 MB/s eta 0:00:04
   -------------------------- ------------- 80.7/122.1 MB 12.5 MB/s eta 0:00:04
   --------------------------- ------------ 83.1/122.1 MB 12.5 MB/s eta 0:00:04
   --------------------------- ------------ 84.9/122.1 MB 12.4 MB/s eta 0:00:04
   ---------------------------- ----------- 87.6/122.1 MB 12.3 MB/s eta 0:00:03
   ----------------------------- ---------- 91.2/122.1 MB 12.4 MB/s eta 0:00:03
   ------------------------------ --------- 94.1/122.1 MB 12.4 MB/s eta 0:00:03
   ------------------------------- -------- 95.4/122.1 MB 12.2 MB/s eta 0:00:03
   -------------------------------- ------- 97.8/122.1 MB 12.2 MB/s eta 0:00:02
   -------------------------------- ------- 99.9/122.1 MB 12.1 MB/s eta 0:00:02
   -------------------------------- ------ 102.5/122.1 MB 12.1 MB/s eta 0:00:02
   --------------------------------- ----- 104.9/122.1 MB 12.0 MB/s eta 0:00:02
   ---------------------------------- ---- 107.7/122.1 MB 12.1 MB/s eta 0:00:02
   ----------------------------------- --- 109.6/122.1 MB 12.0 MB/s eta 0:00:02
   ----------------------------------- --- 109.8/122.1 MB 11.9 MB/s eta 0:00:02
   ----------------------------------- --- 111.4/122.1 MB 11.6 MB/s eta 0:00:01
   ------------------------------------ -- 113.2/122.1 MB 11.6 MB/s eta 0:00:01
   ------------------------------------ -- 114.3/122.1 MB 11.4 MB/s eta 0:00:01
   ------------------------------------- - 116.9/122.1 MB 11.4 MB/s eta 0:00:01
   ------------------------------------- - 118.0/122.1 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- - 118.8/122.1 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  119.5/122.1 MB 11.0 MB/s eta 0:00:01
   --------------------------------------  121.1/122.1 MB 10.9 MB/s eta 0:00:01
   --------------------------------------  121.9/122.1 MB 10.8 MB/s eta 0:00:01
   --------------------------------------  121.9/122.1 MB 10.8 MB/s eta 0:00:01
   --------------------------------------  121.9/122.1 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------- 122.1/122.1 MB 10.3 MB/s  0:00:11
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl (15 kB)
Installing collected packages: mpmath, sympy, networkx, MarkupSafe, jinja2, torch

   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ---------------------------------------- 0/6 [mpmath]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------ --------------------------------- 1/6 [sympy]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   ------------- -------------------------- 2/6 [networkx]
   -------------------- ------------------- 3/6 [MarkupSafe]
   -------------------------- ------------- 4/6 [jinja2]
   -------------------------- ------------- 4/6 [jinja2]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]
   --------------------------------- ------ 5/6 [torch]

In [53]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.13.0+cpu
CUDA available: False

In [55]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("DistilBERT model loaded successfully!")

ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Check out the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

In [56]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

In [57]:
import sys
!{sys.executable} -m pip install torch

Requirement already satisfied: torch in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (2.13.0)
Requirement already satisfied: filelock in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (2026.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from jinja2->torch) (3.0.3)

In [58]:
import torch

print("PyTorch version:", torch.__version__)
print("PyTorch location:", torch.__file__)

PyTorch version: 2.13.0+cpu
PyTorch location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\torch\__init__.py

In [59]:
from transformers import AutoModelForSequenceClassification

print("Transformers + PyTorch are ready!")

Transformers + PyTorch are ready!

In [61]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("DistilBERT loaded successfully!")

ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Check out the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

In [62]:
import sys
import importlib.util

print("Python being used:")
print(sys.executable)

print("\nPyTorch found:")
print(importlib.util.find_spec("torch"))

Python being used:
c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

PyTorch found:
ModuleSpec(name='torch', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000174D0223530>, origin='c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch\\__init__.py', submodule_search_locations=['c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch'])

In [63]:
import sys
!{sys.executable} -m pip install torch

Requirement already satisfied: torch in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (2.13.0)
Requirement already satisfied: filelock in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch) (2026.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from jinja2->torch) (3.0.3)

In [64]:
import torch

print("PyTorch version:", torch.__version__)
print("PyTorch installed successfully!")

PyTorch version: 2.13.0+cpu
PyTorch installed successfully!

In [65]:
import torch

print(torch.__version__)

2.13.0+cpu

In [66]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("DistilBERT loaded successfully!")

ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Check out the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

In [67]:
import sys
import importlib.util

print("Python:")
print(sys.executable)

print("\nPyTorch:")
print(importlib.util.find_spec("torch"))

Python:
c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

PyTorch:
ModuleSpec(name='torch', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000174D0223530>, origin='c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch\\__init__.py', submodule_search_locations=['c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch'])

In [68]:
import sys
import importlib.util

print("Python:")
print(sys.executable)

print("\nPyTorch:")
print(importlib.util.find_spec("torch"))

Python:
c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

PyTorch:
ModuleSpec(name='torch', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000174D0223530>, origin='c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch\\__init__.py', submodule_search_locations=['c:\\Users\\Dell\\anaconda3\\envs\\ruhulstar\\Lib\\site-packages\\torch'])

In [69]:
import torch

print("PyTorch version:", torch.__version__)
print("PyTorch location:", torch.__file__)

PyTorch version: 2.13.0+cpu
PyTorch location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\torch\__init__.py

In [70]:
from transformers import AutoModelForSequenceClassification

print("Transformers can see PyTorch!")

Transformers can see PyTorch!

In [71]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("DistilBERT loaded successfully!")

ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Check out the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

In [72]:
import torch

print("PyTorch version:", torch.__version__)
print("PyTorch location:", torch.__file__)

PyTorch version: 2.13.0+cpu
PyTorch location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\torch\__init__.py

In [73]:
import torch

print("PyTorch version:", torch.__version__)
print("PyTorch location:", torch.__file__)

PyTorch version: 2.13.0+cpu
PyTorch location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\torch\__init__.py

In [74]:
import transformers

print("Transformers version:", transformers.__version__)

Transformers version: 5.15.1

In [75]:
from transformers.utils import is_torch_available

print("PyTorch available to Transformers:", is_torch_available())

PyTorch available to Transformers: False

In [76]:
%pip install --upgrade --force-reinstall transformers

Collecting transformers
  Using cached transformers-5.15.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.28.0-py3-none-any.whl.metadata (16 kB)
Collecting numpy>=1.17 (from transformers)
  Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting packaging>=20.0 (from transformers)
  Using cached packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from transformers)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.7.19-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers)
  Using cached typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers)
  Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting tqdm>=4.60 (from transformers)
  Using cached tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached filelock-3.32.4-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting colorama (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.8.0->typer->transformers)
  Using cached pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached transformers-5.15.1-py3-none-any.whl (11.7 MB)
Using cached huggingface_hub-1.28.0-py3-none-any.whl (793 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached filelock-3.32.4-py3-none-any.whl (99 kB)
Using cached fsspec-2026.7.0-py3-none-any.whl (206 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)
Using cached packaging-26.3-py3-none-any.whl (129 kB)
Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Using cached regex-2026.7.19-cp313-cp313-win_amd64.whl (277 kB)
Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Using cached tqdm-4.70.0-py3-none-any.whl (80 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Using cached idna-3.19-py3-none-any.whl (68 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached typer-0.27.1-py3-none-any.whl (122 kB)
Using cached annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached pygments-2.21.0-py3-none-any.whl (1.3 MB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: typing-extensions, shellingham, safetensors, regex, pyyaml, pygments, packaging, numpy, mdurl, idna, hf-xet, h11, fsspec, filelock, colorama, certifi, annotated-doc, tqdm, markdown-it-py, httpcore, click, anyio, rich, httpx, typer, huggingface-hub, tokenizers, transformers

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.16.0

    Uninstalling typing_extensions-4.16.0:

   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
      Successfully uninstalled typing_extensions-4.16.0
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
   ----------------------------------------  0/28 [typing-extensions]
  Attempting uninstall: shellingham
   ----------------------------------------  0/28 [typing-extensions]
    Found existing installation: shellingham 1.5.4
   ----------------------------------------  0/28 [typing-extensions]
    Uninstalling shellingham-1.5.4:
   ----------------------------------------  0/28 [typing-extensions]
   - --------------------------------------  1/28 [shellingham]
      Successfully uninstalled shellingham-1.5.4
   - --------------------------------------  1/28 [shellingham]
   - --------------------------------------  1/28 [shellingham]
  Attempting uninstall: safetensors
   - --------------------------------------  1/28 [shellingham]
    Found existing installation: safetensors 0.8.0
   - --------------------------------------  1/28 [shellingham]
    Uninstalling safetensors-0.8.0:
   - --------------------------------------  1/28 [shellingham]
      Successfully uninstalled safetensors-0.8.0
   - --------------------------------------  1/28 [shellingham]
   -- -------------------------------------  2/28 [safetensors]
   -- -------------------------------------  2/28 [safetensors]
  Attempting uninstall: regex
   -- -------------------------------------  2/28 [safetensors]
    Found existing installation: regex 2026.7.19
   -- -------------------------------------  2/28 [safetensors]
    Uninstalling regex-2026.7.19:
   -- -------------------------------------  2/28 [safetensors]
   ---- -----------------------------------  3/28 [regex]
      Successfully uninstalled regex-2026.7.19
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
   ---- -----------------------------------  3/28 [regex]
  Attempting uninstall: pyyaml
   ---- -----------------------------------  3/28 [regex]
   ----- ----------------------------------  4/28 [pyyaml]
    Found existing installation: PyYAML 6.0.3
   ----- ----------------------------------  4/28 [pyyaml]
    Uninstalling PyYAML-6.0.3:
   ----- ----------------------------------  4/28 [pyyaml]
      Successfully uninstalled PyYAML-6.0.3
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
   ----- ----------------------------------  4/28 [pyyaml]
  Attempting uninstall: pygments
   ----- ----------------------------------  4/28 [pyyaml]
    Found existing installation: Pygments 2.21.0
   ----- ----------------------------------  4/28 [pyyaml]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
    Uninstalling Pygments-2.21.0:
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
      Successfully uninstalled Pygments-2.21.0
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
   ------- --------------------------------  5/28 [pygments]
  Attempting uninstall: packaging
   ------- --------------------------------  5/28 [pygments]
    Found existing installation: packaging 26.3
   ------- --------------------------------  5/28 [pygments]
    Uninstalling packaging-26.3:
   ------- --------------------------------  5/28 [pygments]
      Successfully uninstalled packaging-26.3
   ------- --------------------------------  5/28 [pygments]
   -------- -------------------------------  6/28 [packaging]
   -------- -------------------------------  6/28 [packaging]
   -------- -------------------------------  6/28 [packaging]
   -------- -------------------------------  6/28 [packaging]
   -------- -------------------------------  6/28 [packaging]
  Attempting uninstall: numpy
   -------- -------------------------------  6/28 [packaging]
    Found existing installation: numpy 2.5.2
   -------- -------------------------------  6/28 [packaging]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
    Uninstalling numpy-2.5.2:
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
      Successfully uninstalled numpy-2.5.2
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]
   ---------- -----------------------------  7/28 [numpy]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\~egex'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\~aml'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\~okenizers'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 5.0.1 requires fsspec[http]<=2026.6.0,>=2023.1.0, but you have fsspec 2026.7.0 which is incompatible.

In [77]:
import torch
import transformers
from transformers.utils import is_torch_available

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PyTorch available to Transformers:", is_torch_available())

PyTorch: 2.13.0+cpu
Transformers: 5.15.1
PyTorch available to Transformers: False

In [78]:
import sys
!{sys.executable} -m pip show torch transformers

Name: torch
Version: 2.13.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author:
Author-email: PyTorch Team <packages@pytorch.org>
License-Expression: Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND MIT
Location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, setuptools, sympy, typing-extensions
Required-by:
---
Name: transformers
Version: 5.15.1
Summary: Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages
Requires: huggingface-hub, numpy, packaging, pyyaml, regex, safetensors, tokenizers, tqdm, typer
Required-by:

In [79]:
import sys
!{sys.executable} -m pip install -U "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (5.15.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (1.28.0)
Requirement already satisfied: numpy>=1.17 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (2.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (4.70.0)
Requirement already satisfied: torch>=2.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers[torch]) (2.13.0)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.16.0)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: anyio in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.14.2)
Requirement already satisfied: certifi in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: psutil in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.2.2)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch>=2.5->transformers[torch]) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch>=2.5->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch>=2.5->transformers[torch]) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from torch>=2.5->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from sympy>=1.13.3->torch>=2.5->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from jinja2->torch>=2.5->transformers[torch]) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from typer->transformers[torch]) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from typer->transformers[torch]) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0

In [80]:
import torch
import transformers
from transformers.utils import is_torch_available

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PyTorch available:", is_torch_available())

PyTorch: 2.13.0+cpu
Transformers: 5.15.1
PyTorch available: False

In [81]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("✅ DistilBERT loaded successfully!")

ImportError:
AutoModelForSequenceClassification requires the PyTorch library but it was not found in your environment. Check out the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

In [82]:
import torch
import transformers

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)

PyTorch: 2.13.0+cpu
Transformers: 5.15.1

In [83]:
from transformers.utils import is_torch_available

print("PyTorch available:", is_torch_available())

PyTorch available: False

In [84]:
import torch
import transformers
from transformers.utils import is_torch_available

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PyTorch available:", is_torch_available())

PyTorch: 2.13.0+cpu
Transformers: 5.15.1
PyTorch available: False

In [85]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

In [86]:
import sys
!{sys.executable} -m pip uninstall transformers -y
!{sys.executable} -m pip install transformers==4.57.1

Found existing installation: transformers 4.57.1
Uninstalling transformers-4.57.1:
  Successfully uninstalled transformers-4.57.1
Collecting transformers==4.57.1
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: filelock in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (3.32.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (2.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (2026.7.19)
Requirement already satisfied: requests in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (2.34.2)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from transformers==4.57.1) (4.70.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (2026.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.16.0)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from tqdm>=4.27->transformers==4.57.1) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from requests->transformers==4.57.1) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from requests->transformers==4.57.1) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from requests->transformers==4.57.1) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\dell\anaconda3\envs\ruhulstar\lib\site-packages (from requests->transformers==4.57.1) (2026.7.22)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Installing collected packages: transformers
Successfully installed transformers-4.57.1

In [88]:
import transformers
import torch
from transformers.utils import is_torch_available

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PyTorch available:", is_torch_available())

PyTorch: 2.13.0+cpu
Transformers: 5.15.1
PyTorch available: False

In [89]:
import sys
import subprocess

print("Notebook Python:")
print(sys.executable)

print("\nInstalling Transformers into THIS Python...")

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--force-reinstall",
    "transformers==4.57.1"
])

Notebook Python:
c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

Installing Transformers into THIS Python...

0

In [91]:
import transformers
import sys

print("Python:", sys.executable)
print("Transformers version:", transformers.__version__)
print("Transformers file:", transformers.__file__)

Python: c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe
Transformers version: 5.15.1
Transformers file: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\transformers\__init__.py

In [92]:
import transformers
import sys

print("Python:", sys.executable)
print("Transformers version:", transformers.__version__)
print("Transformers file:", transformers.__file__)

Python: c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe
Transformers version: 5.15.1
Transformers file: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\transformers\__init__.py

In [93]:
import sys
import transformers

print("Python:", sys.executable)
print("Transformers version:", transformers.__version__)
print("Transformers file:", transformers.__file__)

Python: c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe
Transformers version: 5.15.1
Transformers file: c:\Users\Dell\anaconda3\envs\ruhulstar\Lib\site-packages\transformers\__init__.py

In [96]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "uninstall",
    "transformers",
    "-y"
])

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "transformers==4.57.1"
])

0

In [97]:
import transformers

print(transformers.__version__)

5.15.1

In [98]:
import torch
import transformers

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)

PyTorch: 2.13.0+cpu
Transformers: 5.15.1

In [99]:
from transformers.utils import is_torch_available

print("PyTorch available:", is_torch_available())

PyTorch available: False

In [100]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

In [101]:
conda activate speech_sentiment
python -m ipykernel install --user --name speech_sentiment --display-name "Speech Sentiment"

SyntaxError: invalid syntax (264835106.py, line 1)

In [102]:
import sys
import torch
import transformers

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)

Python: c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe
PyTorch: 2.13.0+cpu
Transformers: 5.15.1

In [103]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\ruhulstar\python.exe

In [1]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe

In [2]:
import sys

print(sys.executable)

c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe

In [3]:
import torch
import transformers

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)

PyTorch: 2.13.0+cpu
Transformers: 4.57.1

In [4]:
from transformers.utils import is_torch_available

print("PyTorch available:", is_torch_available())

PyTorch available: True

In [5]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("✅ DistilBERT loaded successfully!")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dell\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ DistilBERT loaded successfully!

In [1]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

print("✅ Tokenizer loaded successfully!")

✅ Tokenizer loaded successfully!

In [4]:
from pathlib import Path

project = Path.cwd()

print("Notebook location:")
print(project)

print("\nSearching for Amazon file...")

files = list(project.rglob("amazon_cells_labelled.txt"))

for f in files:
    print(f)

Notebook location:
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment

Searching for Amazon file...
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt

In [5]:
from pathlib import Path
import pandas as pd

amazon_path = list(Path.cwd().rglob("amazon_cells_labelled.txt"))[0]

amazon = pd.read_csv(
    amazon_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

print("Amazon:", amazon.shape)
amazon.head()

Amazon: (1000, 2)

                                                text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

In [6]:
imdb_path = list(Path.cwd().rglob("imdb_labelled.txt"))[0]
yelp_path = list(Path.cwd().rglob("yelp_labelled.txt"))[0]

imdb = pd.read_csv(
    imdb_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    yelp_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

print("Amazon:", amazon.shape)
print("IMDB:", imdb.shape)
print("Yelp:", yelp.shape)

Amazon: (1000, 2)
IMDB: (748, 2)
Yelp: (1000, 2)

In [7]:
print("Final dataset shape:", df.shape)
print(df.head())
print(df["label"].value_counts())

NameError: name 'df' is not defined

In [3]:
import pandas as pd

amazon = pd.read_csv(
    r"Dataset\sentiment labelled sentences\sentiment labelled sentences\amazon_cells_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb = pd.read_csv(
    r"Dataset\sentiment labelled sentences\sentiment labelled sentences\imdb_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    r"Dataset\sentiment labelled sentences\sentiment labelled sentences\yelp_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

df = pd.concat([amazon, imdb, yelp], ignore_index=True)

df = df.drop_duplicates().reset_index(drop=True)

print("Final dataset:", df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'Dataset\\sentiment labelled sentences\\sentiment labelled sentences\\amazon_cells_labelled.txt'

In [2]:
train_encodings = tokenizer(
    train_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

print("✅ Tokenization completed!")

NameError: name 'train_df' is not defined

In [ ]:
import torch

class SentimentDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx],
            dtype=torch.long
        )

        return item

    def __len__(self):
        return len(self.labels)

In [ ]:
train_dataset = SentimentDataset(
    train_encodings,
    train_df["label"].tolist()
)

test_dataset = SentimentDataset(
    test_encodings,
    test_df["label"].tolist()
)

print("Training samples:", len(train_dataset))
print("Testing samples:", len(test_dataset))

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

In [8]:
from pathlib import Path

files = list(Path.cwd().rglob("*_labelled.txt"))

print("Files found:")
for f in files:
    print(f)

Files found:
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\imdb_labelled.txt
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\yelp_labelled.txt
c:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\__MACOSX\sentiment labelled sentences\._imdb_labelled.txt

In [9]:
import pandas as pd

amazon_path = list(Path.cwd().rglob("amazon_cells_labelled.txt"))[0]
imdb_path = list(Path.cwd().rglob("imdb_labelled.txt"))[0]
yelp_path = list(Path.cwd().rglob("yelp_labelled.txt"))[0]

amazon = pd.read_csv(
    amazon_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb = pd.read_csv(
    imdb_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    yelp_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

print("Amazon:", amazon.shape)
print("IMDB:", imdb.shape)
print("Yelp:", yelp.shape)

Amazon: (1000, 2)
IMDB: (748, 2)
Yelp: (1000, 2)

In [10]:
df = pd.concat(
    [amazon, imdb, yelp],
    ignore_index=True
)

df = df.drop_duplicates().reset_index(drop=True)

print("Final dataset shape:", df.shape)
print(df.head())
print(df["label"].value_counts())

Final dataset shape: (2731, 2)
                                                text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1
label
1    1376
0    1355
Name: count, dtype: int64

In [11]:
df

                                                   text  label
0     So there is no way for me to plug it in here i...      0
1                           Good case, Excellent value.      1
2                                Great for the jawbone.      1
3     Tied to charger for conversations lasting more...      0
4                                     The mic is great.      1
...                                                 ...    ...
2726  I think food should have flavor and texture an...      0
2727                           Appetite instantly gone.      0
2728  Overall I was not impressed and would not go b...      0
2729  The whole experience was underwhelming, and I ...      0
2730  Then, as if I hadn't wasted enough of my life ...      0

[2731 rows x 2 columns]

In [12]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print("Training data:", train_df.shape)
print("Testing data:", test_df.shape)

Training data: (2184, 2)
Testing data: (547, 2)

In [13]:
print("Training labels:")
print(train_df["label"].value_counts())

print("\nTesting labels:")
print(test_df["label"].value_counts())

Training labels:
label
1    1100
0    1084
Name: count, dtype: int64

Testing labels:
label
1    276
0    271
Name: count, dtype: int64

In [14]:
train_encodings = tokenizer(
    train_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

print("✅ Tokenization completed!")

✅ Tokenization completed!

In [15]:
print(train_encodings.keys())
print("Training samples:", len(train_encodings["input_ids"]))

KeysView({'input_ids': [[101, 2065, 2017, 2215, 1037, 2613, 12665, 9278, 2023, 2028, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2009, 2001, 7570, 14343, 15482, 2271, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 2069, 2825, 2126, 2023, 3185, 2071, 2022, 2417, 21564, 2098, 2052, 2022, 2004, 5796, 2102, 2509, 2243, 1042, 7716, 4063, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2651, 2001, 2026, 2034, 5510, 1997, 1037, 20934, 6392, 8649, 2483, 2175, 3126, 11368, 2980, 3899, 1998, 1045, 2031, 2000, 2425, 2017, 2009, 2001, 2062, 2084, 1045, 2412, 2245, 2825, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2020, 12181, 2015, 2006, 1996, 3042, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 3376, 20724, 2295, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2428, 5632, 5983, 2182, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 12455, 2012, 8064, 2467, 2191, 2149, 2514, 2061, 6160, 1998, 2569, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2059, 1037, 2261, 2420, 2101, 1996, 1037, 23893, 1997, 5610, 2234, 2041, 1997, 1996, 3042, 2096, 1999, 2224, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2057, 2018, 1021, 2012, 2256, 2795, 1998, 1996, 2326, 2001, 3492, 3435, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 3269, 4948, 6558, 2630, 19392, 24970, 4765, 4965, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2292, 1005, 1055, 2707, 2007, 2035, 1996, 3471, 10760, 3772, 1010, 2926, 2013, 1996, 2599, 2934, 1010, 2001, 2200, 1010, 2200, 2919, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 15610, 2347, 1005, 1056, 14044, 2030, 5379, 1998, 6524, 7039, 2006, 2149, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2326, 2003, 4248, 1998, 2130, 1000, 2000, 2175, 1000, 4449, 2024, 2074, 2066, 2057, 2066, 2009, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 5993, 2007, 8201, 1010, 2023, 3185, 2003, 3492, 2919, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 4149, 3701, 2005, 1996, 3715, 2099, 1010, 2029, 3631, 2574, 2044, 13131, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2833, 2001, 2779, 2012, 2190, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 4684, 3042, 5906, 2024, 1037, 2442, 2031, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 1005, 1040, 18012, 3087, 2000, 2175, 1998, 2156, 2009, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2204, 5404, 1004, 4392, 4989, 1998, 2204, 2833, 4989, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 5102, 2039, 2000, 2022, 5845, 2061, 12726, 2135, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 6854, 1010, 1005, 3104, 2611, 1005, 2003, 2019, 2742, 1997, 2129, 5365, 2109, 2000, 18077, 2308, 2005, 3361, 5114, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2009, 1005, 1055, 2019, 4064, 1010, 8892, 5806, 1997, 1037, 3185, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2037, 20209, 24182, 2003, 2061, 2204, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2119, 3152, 2024, 6659, 1010, 2021, 2000, 1996, 4923, 1997, 1996, 3069, 2544, 1010, 2009, 2001, 3422, 3085, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2307, 2173, 1042, 2080, 2202, 2041, 2030, 4521, 1999, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2613, 10514, 6182, 10205, 1010, 2292, 1005, 1055, 2022, 7481, 1011, 8038, 2863, 2003, 2025, 2008, 2204, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2027, 2562, 2893, 2488, 1998, 2488, 1006, 2023, 2003, 2026, 2353, 2028, 1998, 1045, 1005, 2310, 2018, 3365, 9486, 2205, 1007, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2023, 2173, 2003, 2025, 4276, 2115, 2051, 1010, 2292, 2894, 7136, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2097, 5791, 2022, 2067, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2123, 1005, 1056, 3404, 2037, 4037, 1998, 2123, 1005, 1056, 5987, 2151, 14044, 2490, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2031, 6749, 2009, 2000, 2814, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 10166, 1010, 2054, 1037, 2919, 2143, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 9043, 5571, 2005, 2023, 2326, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2200, 3407, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2200, 4487, 13102, 19738, 6924, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2821, 3398, 1010, 1998, 1996, 9994, 2001, 17203, 2205, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 4540, 12439, 2015, 3149, 1996, 2614, 3495, 2046, 2115, 4540, 1998, 4025, 2000, 3623, 1996, 2614, 3872, 1998, 15563, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2009, 2038, 2042, 1037, 3453, 2005, 2149, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2119, 2307, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 1000, 7738, 1000, 1997, 1996, 3806, 7286, 2012, 1996, 2203, 2001, 2074, 2004, 9643, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2204, 2553, 1010, 6581, 3643, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1996, 3898, 2946, 2003, 2502, 1010, 3145, 11687, 5507, 2092, 2438, 1010, 1998, 1996, 4950, 3737, 2003, 6581, 2005, 1037, 4950, 3042, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2327, 2240, 1024, 2123, 1005, 1056, 5949, 2115, 2051, 1998, 2769, 2006, 2023, 2028, 1010, 2049, 2004, 2919, 2004, 2009, 3310, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2465, 2100, 1013, 4010, 7224, 1010, 4569, 1998, 4840, 10439, 20624, 16750, 1010, 10514, 9468, 27581, 21475, 2015, 1006, 3598, 21475, 999, 999, 999, 999, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2515, 2025, 3715, 1996, 25022, 3070, 7934, 1006, 2012, 2102, 1007, 5594, 17788, 3042, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2256, 8241, 2001, 2200, 3835, 1010, 1998, 2130, 2295, 2002, 2246, 1037, 2210, 13394, 2007, 2035, 1997, 2256, 3791, 1010, 2002, 4370, 2658, 1998, 5379, 2127, 1996, 2203, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [16]:
import torch

class SentimentDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx],
            dtype=torch.long
        )

        return item

    def __len__(self):
        return len(self.labels)

In [17]:
train_dataset = SentimentDataset(
    train_encodings,
    train_df["label"].tolist()
)

test_dataset = SentimentDataset(
    test_encodings,
    test_df["label"].tolist()
)

print("Training samples:", len(train_dataset))
print("Testing samples:", len(test_dataset))

Training samples: 2184
Testing samples: 547

In [18]:
sample = train_dataset[0]

print(sample.keys())
print("Input IDs:", sample["input_ids"].shape)
print("Attention Mask:", sample["attention_mask"].shape)
print("Label:", sample["labels"])

dict_keys(['input_ids', 'attention_mask', 'labels'])
Input IDs: torch.Size([128])
Attention Mask: torch.Size([128])
Label: tensor(1)

In [19]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary"
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [21]:
%pip install "accelerate>=0.26.0"

Collecting accelerate>=0.26.0
  Using cached accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (26.3)
Requirement already satisfied: psutil in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (7.2.2)
Requirement already satisfied: pyyaml in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (2.13.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (0.36.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate>=0.26.0) (0.8.0)
Requirement already satisfied: filelock in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (2026.6.0)
Requirement already satisfied: requests in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (2.34.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (4.70.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=2.0.0->accelerate>=0.26.0) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=2.0.0->accelerate>=0.26.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=0.26.0) (1.3.0)
Requirement already satisfied: colorama in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate>=0.26.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate>=0.26.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (2026.7.22)
Using cached accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0
Note: you may need to restart the kernel to use updated packages.

In [22]:
import torch
import accelerate
import transformers

print("PyTorch:", torch.__version__)
print("Accelerate:", accelerate.__version__)
print("Transformers:", transformers.__version__)

PyTorch: 2.13.0+cpu
Accelerate: 1.14.0
Transformers: 4.57.1

In [23]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

print("✅ Training configuration created!")

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`

In [20]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

print("✅ Training configuration created!")

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`

In [24]:
import sys
import torch
import accelerate
import transformers

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Accelerate:", accelerate.__version__)
print("Transformers:", transformers.__version__)

Python: c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe
PyTorch: 2.13.0+cpu
Accelerate: 1.14.0
Transformers: 4.57.1

In [25]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

print("✅ Training configuration created!")

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`

In [26]:
import sys
import torch
import transformers

print("Python:")
print(sys.executable)

print("\nPyTorch:")
print(torch.__version__)

print("\nTransformers:")
print(transformers.__version__)

try:
    import accelerate
    print("\nAccelerate:")
    print(accelerate.__version__)
    print(accelerate.__file__)
except Exception as e:
    print("\nAccelerate ERROR:")
    print(repr(e))

print("\nTransformers sees PyTorch:")
print(transformers.utils.is_torch_available())

print("\nTransformers sees Accelerate:")
print(transformers.utils.is_accelerate_available())

Python:
c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe

PyTorch:
2.13.0+cpu

Transformers:
4.57.1

Accelerate:
1.14.0
c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages\accelerate\__init__.py

Transformers sees PyTorch:
True

Transformers sees Accelerate:
False

In [27]:
import torch
import transformers
import accelerate

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)

print("Transformers sees PyTorch:",
      transformers.utils.is_torch_available())

print("Transformers sees Accelerate:",
      transformers.utils.is_accelerate_available())

PyTorch: 2.13.0+cpu
Transformers: 4.57.1
Accelerate: 1.14.0
Transformers sees PyTorch: True
Transformers sees Accelerate: False

In [29]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to="none"
)

print("✅ TrainingArguments created successfully!")

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`

In [30]:
import sys
import torch
import accelerate
import transformers

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Accelerate:", accelerate.__version__)
print("Transformers:", transformers.__version__)

from transformers.utils import is_accelerate_available

print("Accelerate available to Transformers:", is_accelerate_available())

Python: c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe
PyTorch: 2.13.0+cpu
Accelerate: 1.14.0
Transformers: 4.57.1
Accelerate available to Transformers: False

In [31]:
import sys

!{sys.executable} -m pip uninstall -y transformers accelerate

Found existing installation: transformers 4.46.3
Uninstalling transformers-4.46.3:
  Successfully uninstalled transformers-4.46.3
Found existing installation: accelerate 0.34.2
Uninstalling accelerate-0.34.2:
  Successfully uninstalled accelerate-0.34.2

In [32]:
!{sys.executable} -m pip install transformers==4.46.3 accelerate==0.34.2

Collecting transformers==4.46.3
  Using cached transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
Collecting accelerate==0.34.2
  Using cached accelerate-0.34.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (3.32.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (2026.7.19)
Requirement already satisfied: requests in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (2.34.2)
Requirement already satisfied: tokenizers<0.21,>=0.20 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from transformers==4.46.3) (4.70.0)
Requirement already satisfied: psutil in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate==0.34.2) (7.2.2)
Requirement already satisfied: torch>=1.10.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from accelerate==0.34.2) (2.13.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2026.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=1.10.0->accelerate==0.34.2) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=1.10.0->accelerate==0.34.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=1.10.0->accelerate==0.34.2) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from torch>=1.10.0->accelerate==0.34.2) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.34.2) (1.3.0)
Requirement already satisfied: colorama in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from tqdm>=4.27->transformers==4.46.3) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from jinja2->torch>=1.10.0->accelerate==0.34.2) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->transformers==4.46.3) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->transformers==4.46.3) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->transformers==4.46.3) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Dell\anaconda3\envs\speech_sentiment\Lib\site-packages (from requests->transformers==4.46.3) (2026.7.22)
Using cached transformers-4.46.3-py3-none-any.whl (10.0 MB)
Using cached accelerate-0.34.2-py3-none-any.whl (324 kB)
Installing collected packages: accelerate, transformers

   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   ---------------------------------------- 0/2 [accelerate]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   -------------------- ------------------- 1/2 [transformers]
   ---------------------------------------- 2/2 [transformers]

Successfully installed accelerate-0.34.2 transformers-4.46.3

In [33]:
import sys
import torch
import accelerate
import transformers
from transformers.utils import is_accelerate_available

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Accelerate:", accelerate.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate available:", is_accelerate_available())

Python: c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe
PyTorch: 2.13.0+cpu
Accelerate: 1.14.0
Transformers: 4.57.1
Accelerate available: False

In [34]:
import sys
import importlib.util

print("Python:", sys.executable)

print("\nAccelerate spec:")
print(importlib.util.find_spec("accelerate"))

print("\nTransformers spec:")
print(importlib.util.find_spec("transformers"))

print("\nAccelerate version:")
import accelerate
print(accelerate.__version__)

print("\nTransformers version:")
import transformers
print(transformers.__version__)

Python: c:\Users\Dell\anaconda3\envs\speech_sentiment\python.exe

Accelerate spec:
ModuleSpec(name='accelerate', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000014D6EB00050>, origin='c:\\Users\\Dell\\anaconda3\\envs\\speech_sentiment\\Lib\\site-packages\\accelerate\\__init__.py', submodule_search_locations=['c:\\Users\\Dell\\anaconda3\\envs\\speech_sentiment\\Lib\\site-packages\\accelerate'])

Transformers spec:
ModuleSpec(name='transformers', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000014D7A8E6790>, origin='c:\\Users\\Dell\\anaconda3\\envs\\speech_sentiment\\Lib\\site-packages\\transformers\\__init__.py', submodule_search_locations=['c:\\Users\\Dell\\anaconda3\\envs\\speech_sentiment\\Lib\\site-packages\\transformers'])

Accelerate version:
1.14.0

Transformers version:
4.57.1

In [35]:
from transformers.utils import is_accelerate_available
from transformers.utils import is_torch_available

print("Torch available:", is_torch_available())
print("Accelerate available:", is_accelerate_available())

Torch available: True
Accelerate available: False

In [36]:
import os

print("ACCELERATE_DISABLE:", os.environ.get("ACCELERATE_DISABLE"))
print("TRANSFORMERS_NO_ADVISORY_WARNINGS:", os.environ.get("TRANSFORMERS_NO_ADVISORY_WARNINGS"))

ACCELERATE_DISABLE: None
TRANSFORMERS_NO_ADVISORY_WARNINGS: None

In [1]:
import sys
import torch
import transformers
import accelerate

from transformers.utils import is_torch_available, is_accelerate_available

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("Torch available:", is_torch_available())
print("Accelerate available:", is_accelerate_available())

c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Python: c:\Users\Dell\anaconda3\envs\speech_final\python.exe
PyTorch: 2.13.0+cpu
Transformers: 4.46.3
Accelerate: 0.34.2
Torch available: True
Accelerate available: True

In [2]:
import pandas as pd

base_path = r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment labelled sentences\sentiment labelled sentences"

amazon = pd.read_csv(
    base_path + r"\amazon_cells_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb = pd.read_csv(
    base_path + r"\imdb_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    base_path + r"\yelp_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

df = pd.concat([amazon, imdb, yelp], ignore_index=True)

print("Final dataset shape:", df.shape)
print(df.head())
print("\nLabel distribution:")
print(df["label"].value_counts())

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dell\\OneDrive\\Desktop\\Speech_to_Text_Sentiment\\Dataset\\sentiment labelled sentences\\sentiment labelled sentences\\amazon_cells_labelled.txt'

In [3]:
from pathlib import Path

dataset_folder = Path(
    r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset"
)

matches = list(dataset_folder.rglob("amazon_cells_labelled.txt"))

print("Found:", len(matches))

for file in matches:
    print(file)

Found: 1
C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment+labelled+sentences\sentiment labelled sentences\amazon_cells_labelled.txt

In [4]:
import pandas as pd

base_path = r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset\sentiment labelled sentences\sentiment labelled sentences"

amazon = pd.read_csv(
    base_path + r"\amazon_cells_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb = pd.read_csv(
    base_path + r"\imdb_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    base_path + r"\yelp_labelled.txt",
    sep="\t",
    header=None,
    names=["text", "label"]
)

df = pd.concat([amazon, imdb, yelp], ignore_index=True)

print("Final dataset shape:", df.shape)
print(df.head())
print("\nLabel distribution:")
print(df["label"].value_counts())

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dell\\OneDrive\\Desktop\\Speech_to_Text_Sentiment\\Dataset\\sentiment labelled sentences\\sentiment labelled sentences\\amazon_cells_labelled.txt'

In [5]:
import pandas as pd
from pathlib import Path

dataset_folder = Path(
    r"C:\Users\Dell\OneDrive\Desktop\Speech_to_Text_Sentiment\Dataset"
)

# Find files automatically
amazon_path = next(dataset_folder.rglob("amazon_cells_labelled.txt"))
imdb_path = next(dataset_folder.rglob("imdb_labelled.txt"))
yelp_path = next(dataset_folder.rglob("yelp_labelled.txt"))

# Load datasets
amazon = pd.read_csv(
    amazon_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

imdb = pd.read_csv(
    imdb_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

yelp = pd.read_csv(
    yelp_path,
    sep="\t",
    header=None,
    names=["text", "label"]
)

# Combine
df = pd.concat(
    [amazon, imdb, yelp],
    ignore_index=True
)

print("Amazon:", amazon.shape)
print("IMDB:", imdb.shape)
print("Yelp:", yelp.shape)
print("Final dataset:", df.shape)

print("\nFirst 5 rows:")
print(df.head())

print("\nLabel distribution:")
print(df["label"].value_counts())

Amazon: (1000, 2)
IMDB: (748, 2)
Yelp: (1000, 2)
Final dataset: (2748, 2)

First 5 rows:
                                                text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

Label distribution:
label
1    1386
0    1362
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print("Training:", train_df.shape)
print("Testing:", test_df.shape)

Training: (2198, 2)
Testing: (550, 2)

In [7]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(
    train_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

print("✅ Tokenization completed")

✅ Tokenization completed

In [8]:
import torch

class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }
        item["labels"] = torch.tensor(
            self.labels[idx],
            dtype=torch.long
        )
        return item

    def __len__(self):
        return len(self.labels)


train_dataset = SentimentDataset(
    train_encodings,
    train_df["label"].tolist()
)

test_dataset = SentimentDataset(
    test_encodings,
    test_df["label"].tolist()
)

print("✅ PyTorch datasets created")
print("Train:", len(train_dataset))
print("Test:", len(test_dataset))

✅ PyTorch datasets created
Train: 2198
Test: 550

In [9]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

print("✅ DistilBERT model loaded")

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ DistilBERT model loaded

In [10]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./models/distilbert_sentiment",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to="none"
)

print("✅ Training arguments ready")

✅ Training arguments ready

In [11]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

print("✅ Trainer ready")

✅ Trainer ready

In [12]:
trainer.train()

  0%|          | 0/825 [00:00<?, ?it/s]c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
  6%|▌         | 50/825 [03:47<55:12,  4.27s/it]

{'loss': 0.5599, 'grad_norm': 6.579165935516357, 'learning_rate': 1.8787878787878792e-05, 'epoch': 0.18}

 12%|█▏        | 100/825 [07:34<54:12,  4.49s/it]

{'loss': 0.3232, 'grad_norm': 10.096501350402832, 'learning_rate': 1.7575757575757576e-05, 'epoch': 0.36}

 18%|█▊        | 150/825 [11:09<46:47,  4.16s/it]

{'loss': 0.2228, 'grad_norm': 42.24387741088867, 'learning_rate': 1.6363636363636366e-05, 'epoch': 0.55}

 24%|██▍       | 200/825 [14:36<44:13,  4.25s/it]

{'loss': 0.296, 'grad_norm': 7.929276466369629, 'learning_rate': 1.5151515151515153e-05, 'epoch': 0.73}

 30%|███       | 250/825 [18:14<41:36,  4.34s/it]

{'loss': 0.2372, 'grad_norm': 2.6297593116760254, 'learning_rate': 1.3939393939393942e-05, 'epoch': 0.91}

 33%|███▎      | 275/825 [21:01<35:46,  3.90s/it]

{'eval_loss': 0.31665781140327454, 'eval_runtime': 63.7709, 'eval_samples_per_second': 8.625, 'eval_steps_per_second': 1.082, 'epoch': 1.0}

c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
 36%|███▋      | 300/825 [22:56<39:02,  4.46s/it]

{'loss': 0.2353, 'grad_norm': 0.737453818321228, 'learning_rate': 1.2727272727272728e-05, 'epoch': 1.09}

 42%|████▏     | 350/825 [26:40<32:56,  4.16s/it]

{'loss': 0.1125, 'grad_norm': 0.16689373552799225, 'learning_rate': 1.1515151515151517e-05, 'epoch': 1.27}

 48%|████▊     | 400/825 [30:18<30:39,  4.33s/it]

{'loss': 0.171, 'grad_norm': 0.2059331089258194, 'learning_rate': 1.0303030303030304e-05, 'epoch': 1.45}

 55%|█████▍    | 450/825 [34:11<27:54,  4.46s/it]

{'loss': 0.1255, 'grad_norm': 2.3588080406188965, 'learning_rate': 9.090909090909091e-06, 'epoch': 1.64}

 61%|██████    | 500/825 [37:49<23:10,  4.28s/it]

{'loss': 0.1029, 'grad_norm': 0.9778467416763306, 'learning_rate': 7.87878787878788e-06, 'epoch': 1.82}

 67%|██████▋   | 550/825 [41:37<19:15,  4.20s/it]

{'loss': 0.1664, 'grad_norm': 0.06640265136957169, 'learning_rate': 6.666666666666667e-06, 'epoch': 2.0}

 67%|██████▋   | 550/825 [42:52<19:15,  4.20s/it]

{'eval_loss': 0.2814200818538666, 'eval_runtime': 75.5952, 'eval_samples_per_second': 7.276, 'eval_steps_per_second': 0.913, 'epoch': 2.0}

c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
 73%|███████▎  | 600/825 [47:15<20:41,  5.52s/it]

{'loss': 0.043, 'grad_norm': 0.0687280222773552, 'learning_rate': 5.4545454545454545e-06, 'epoch': 2.18}

 79%|███████▉  | 650/825 [51:42<15:10,  5.20s/it]

{'loss': 0.0863, 'grad_norm': 20.154468536376953, 'learning_rate': 4.242424242424243e-06, 'epoch': 2.36}

 85%|████████▍ | 700/825 [56:00<09:48,  4.71s/it]

{'loss': 0.0668, 'grad_norm': 0.16555702686309814, 'learning_rate': 3.0303030303030305e-06, 'epoch': 2.55}

 91%|█████████ | 750/825 [59:22<05:02,  4.04s/it]

{'loss': 0.0413, 'grad_norm': 0.770344614982605, 'learning_rate': 1.8181818181818183e-06, 'epoch': 2.73}

 97%|█████████▋| 800/825 [1:02:57<01:44,  4.19s/it]

{'loss': 0.0563, 'grad_norm': 0.05390302091836929, 'learning_rate': 6.060606060606061e-07, 'epoch': 2.91}

100%|██████████| 825/825 [1:04:46<00:00,  4.47s/it]c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

100%|██████████| 825/825 [1:05:54<00:00,  4.47s/it]

{'eval_loss': 0.31169599294662476, 'eval_runtime': 65.9577, 'eval_samples_per_second': 8.339, 'eval_steps_per_second': 1.046, 'epoch': 3.0}

100%|██████████| 825/825 [1:05:56<00:00,  4.80s/it]

{'train_runtime': 3956.6245, 'train_samples_per_second': 1.667, 'train_steps_per_second': 0.209, 'train_loss': 0.17267854674295946, 'epoch': 3.0}

TrainOutput(global_step=825, training_loss=0.17267854674295946, metrics={'train_runtime': 3956.6245, 'train_samples_per_second': 1.667, 'train_steps_per_second': 0.209, 'total_flos': 218372506684416.0, 'train_loss': 0.17267854674295946, 'epoch': 3.0})

In [13]:
results = trainer.evaluate()

print("✅ Evaluation completed")
print(results)

c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
100%|██████████| 69/69 [01:18<00:00,  1.13s/it]

✅ Evaluation completed
{'eval_loss': 0.31169599294662476, 'eval_runtime': 79.2349, 'eval_samples_per_second': 6.941, 'eval_steps_per_second': 0.871, 'epoch': 3.0}

In [14]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

predictions = trainer.predict(test_dataset)

pred_labels = np.argmax(
    predictions.predictions,
    axis=1
)

true_labels = test_df["label"].values

accuracy = accuracy_score(
    true_labels,
    pred_labels
)

print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        true_labels,
        pred_labels,
        target_names=["Negative", "Positive"]
    )
)

100%|██████████| 69/69 [01:20<00:00,  1.17s/it]

Accuracy: 0.9255

Classification Report:
              precision    recall  f1-score   support

    Negative       0.90      0.95      0.93       273
    Positive       0.95      0.90      0.92       277

    accuracy                           0.93       550
   macro avg       0.93      0.93      0.93       550
weighted avg       0.93      0.93      0.93       550

In [15]:
model_path = "./models/distilbert_sentiment"

trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)

print("✅ Model saved successfully!")
print("Location:", model_path)

✅ Model saved successfully!
Location: ./models/distilbert_sentiment

In [16]:
from transformers import pipeline
sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="./models/distilbert_sentiment",
    tokenizer="./models/distilbert_sentiment"
)
text = input("i love u")
result = sentiment_pipeline(text)
print(result)

[{'label': 'LABEL_1', 'score': 0.9063781499862671}]

In [17]:
results = trainer.evaluate()

print("✅ Evaluation completed")
print(results)

c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
100%|██████████| 69/69 [01:24<00:00,  1.22s/it]

✅ Evaluation completed
{'eval_loss': 0.31169599294662476, 'eval_runtime': 92.0826, 'eval_samples_per_second': 5.973, 'eval_steps_per_second': 0.749, 'epoch': 3.0}

In [18]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

predictions = trainer.predict(test_dataset)

pred_labels = np.argmax(
    predictions.predictions,
    axis=1
)

true_labels = test_df["label"].values

accuracy = accuracy_score(true_labels, pred_labels)

print(f"\nAccuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        true_labels,
        pred_labels,
        target_names=["Negative", "Positive"]
    )
)

100%|██████████| 69/69 [01:09<00:00,  1.00s/it]

Accuracy: 92.55%

Classification Report:
              precision    recall  f1-score   support

    Negative       0.90      0.95      0.93       273
    Positive       0.95      0.90      0.92       277

    accuracy                           0.93       550
   macro avg       0.93      0.93      0.93       550
weighted avg       0.93      0.93      0.93       550

In [19]:
model_path = "./models/distilbert_sentiment"

trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)

print("✅ Model saved successfully!")

✅ Model saved successfully!

In [20]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="./models/distilbert_sentiment",
    tokenizer="./models/distilbert_sentiment"
)

text = input("I LOVE U")

result = sentiment_pipeline(text)

label = result[0]["label"]
score = result[0]["score"]

if label == "LABEL_1":
    sentiment = "POSITIVE"
else:
    sentiment = "NEGATIVE"

print("Sentiment:", sentiment)
print("Confidence:", f"{score * 100:.2f}%")

Sentiment: POSITIVE
Confidence: 90.64%

In [21]:
model.save_pretrained("./models/distilbert_sentiment")
tokenizer.save_pretrained("./models/distilbert_sentiment")

print("✅ Model and tokenizer saved successfully!")

✅ Model and tokenizer saved successfully!

In [23]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="./models/distilbert_sentiment",
    tokenizer="./models/distilbert_sentiment"
)

text = input("I LOVE U THIS PROJECT ")

result = sentiment_pipeline(text)[0]

print("Sentiment:", result["label"])
print("Confidence:", f"{result['score'] * 100:.2f}%")

Sentiment: LABEL_1
Confidence: 90.64%

In [24]:
model.config.id2label = {
    0: "NEGATIVE",
    1: "POSITIVE"
}

model.config.label2id = {
    "NEGATIVE": 0,
    "POSITIVE": 1
}

print(model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [25]:
model.save_pretrained("./models/distilbert_sentiment")
tokenizer.save_pretrained("./models/distilbert_sentiment")

print("✅ Model saved with correct labels!")

✅ Model saved with correct labels!

In [28]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="./models/distilbert_sentiment",
    tokenizer="./models/distilbert_sentiment"
)

text = input(" I LOVE U ")

result = sentiment_pipeline(text)[0]

print("Sentiment:", result["label"])
print("Confidence:", f"{result['score'] * 100:.2f}%")

Sentiment: POSITIVE
Confidence: 90.64%

In [34]:
import sounddevice as sd
import scipy.io.wavfile as wav
import speech_recognition as sr

duration = 5
sample_rate = 16000

print("🎤 Speak now...")

audio = sd.rec(
    int(duration * sample_rate),
    samplerate=sample_rate,
    channels=1,
    dtype="int16"
)

sd.wait()

wav.write("voice_input.wav", sample_rate, audio)

print("✅ Recording completed!")

recognizer = sr.Recognizer()

with sr.AudioFile("voice_input.wav") as source:
    recorded_audio = recognizer.record(source)

print("🔄 Converting speech to text...")

text = recognizer.recognize_google(recorded_audio)

print("📝 You said:", text)

🎤 Speak now...
✅ Recording completed!
🔄 Converting speech to text...
📝 You said: I love Warangal

In [30]:
import sys
!{sys.executable} -m pip install sounddevice scipy SpeechRecognition

Collecting sounddevice
  Using cached sounddevice-0.5.6-py3-none-win_amd64.whl.metadata (1.4 kB)
Requirement already satisfied: scipy in c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages (1.17.1)
Collecting SpeechRecognition
  Using cached speechrecognition-3.17.0-py3-none-any.whl.metadata (28 kB)
Collecting cffi (from sounddevice)
  Using cached cffi-2.1.1-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages (from scipy) (2.4.6)
Requirement already satisfied: typing-extensions in c:\Users\Dell\anaconda3\envs\speech_final\Lib\site-packages (from SpeechRecognition) (4.16.0)
Collecting pycparser (from cffi->sounddevice)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Using cached sounddevice-0.5.6-py3-none-win_amd64.whl (1.0 MB)
Using cached speechrecognition-3.17.0-py3-none-any.whl (32.9 MB)
Using cached cffi-2.1.1-cp311-cp311-win_amd64.whl (185 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: SpeechRecognition, pycparser, cffi, sounddevice

   ---------------------------------------- 0/4 [SpeechRecognition]
   ---------------------------------------- 0/4 [SpeechRecognition]
   ---------------------------------------- 0/4 [SpeechRecognition]
   ---------- ----------------------------- 1/4 [pycparser]
   -------------------- ------------------- 2/4 [cffi]
   -------------------- ------------------- 2/4 [cffi]
   -------------------- ------------------- 2/4 [cffi]
   ------------------------------ --------- 3/4 [sounddevice]
   ---------------------------------------- 4/4 [sounddevice]

Successfully installed SpeechRecognition-3.17.0 cffi-2.1.1 pycparser-3.0 sounddevice-0.5.6

In [35]:
import sounddevice as sd
import scipy.io.wavfile as wav
import speech_recognition as sr

print("✅ Audio libraries loaded!")

✅ Audio libraries loaded!

In [37]:
import sounddevice as sd
import scipy.io.wavfile as wav
import speech_recognition as sr

duration = 5
sample_rate = 16000

print("🎤 Speak now...")

audio = sd.rec(
    int(duration * sample_rate),
    samplerate=sample_rate,
    channels=1,
    dtype="int16"
)

sd.wait()

wav.write("voice_input.wav", sample_rate, audio)

print("✅ Recording completed!")

recognizer = sr.Recognizer()

with sr.AudioFile("voice_input.wav") as source:
    recorded_audio = recognizer.record(source)

print("🔄 Converting speech to text...")

text = recognizer.recognize_google(recorded_audio)

print("📝 You said:", text)

🎤 Speak now...

✅ Recording completed!
🔄 Converting speech to text...
📝 You said: I hate you I hate you I

In [38]:
result = sentiment_pipeline(text)[0]

print("📝 Text:", text)
print("🎯 Sentiment:", result["label"])
print("📊 Confidence:", f"{result['score'] * 100:.2f}%")

📝 Text: I hate you I hate you I
🎯 Sentiment: NEGATIVE
📊 Confidence: 99.55%